version: '3.4'

services:
  hepsiorada.api:
    image: ${DOCKER_REGISTRY-}hepsioradaapi
    container_name: hepsiorada.api
    build:
      context: .
      dockerfile: Hepsiorada.Api/Dockerfile
    ports:
      - "1881:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  postgres:
    image: postgres
    container_name: postgres
    volumes:     
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hepsioradadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - dev
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
     - "6379:6379"
    networks:
      - dev
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
     MONGO_INITDB_DATABASE: hepsiorada
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017" 
networks:
  dev:
    name: dev_network
    driver: bridge
volumes:
  postgres_data:
  mongo_data:
  mongo_config: